version: "3.8"
services:
  n8n:
    image: n8nio/n8n:1.69.0
    restart: always
    ports:
      - "80:5678"
    environment:
      - N8N_HOST=n8n.pepper88.com
      - NODE_ENV=production
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=http://n8n.pepper88.com
      - WEBHOOK_URL=http://n8n.pepper88.com
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data: