name: Release Dagger Module

on:
  workflow_call:
    inputs:
      module-path:
        description: "Path to the Dagger module"
        required: false
        type: string
        default: "."
    secrets:
      GITHUB_TOKEN:
        required: true

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dagger/dagger-for-github@v7
        with:
          version: "0.15.1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: |
          cd .dagger/release && go run release.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
