title: Daggerverse Documentation
description: Documentation for Daggerverse modules and libraries
remote_theme: just-the-docs/just-the-docs@v0.5.2

url: https://felipepimentel.github.io
baseurl: "/daggerverse"

# Theme settings
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

# Enable or disable the site search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository": 
    - "https://github.com/felipepimentel/daggerverse"
aux_links_new_tab: true

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2024 Felipe Pimentel. Distributed under the <a href=\"https://github.com/felipepimentel/daggerverse/blob/main/LICENSE\">Apache License 2.0.</a>"

# Collections for organizing content
collections:
  libraries:
    permalink: "/:collection/:path"
    output: true
  essentials:
    permalink: "/:collection/:path"
    output: true

# Enable or disable heading anchors
heading_anchors: true

# Enable or disable copy buttons on code blocks
enable_copy_code_button: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/felipepimentel/daggerverse"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: blue

# Default YAML front matter
defaults:
  - scope:
      path: ""
      type: libraries
    values:
      layout: default
      parent: Libraries
  - scope:
      path: ""
      type: essentials
    values:
      layout: default
      parent: Essentials 