title: Daggerverse Documentation
description: Documentation for Daggerverse modules and libraries
remote_theme: just-the-docs/just-the-docs@v0.5.2

url: https://felipepimentel.github.io
baseurl: "/daggerverse"

# Theme settings
heading_anchors: true
color_scheme: dark
search_enabled: true
enable_copy_code_button: true

# Navigation
nav_external_links:
  - title: Dagger Documentation
    url: https://docs.dagger.io
    hide_icon: false
  - title: GitHub Repository
    url: https://github.com/felipepimentel/daggerverse
    hide_icon: false

# Aux links
aux_links:
  "View on GitHub":
    - "https://github.com/felipepimentel/daggerverse"
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2024 Felipe Pimentel. Distributed under the <a href=\"https://github.com/felipepimentel/daggerverse/blob/main/LICENSE\">Apache License 2.0.</a>"

# Collections
collections:
  libraries:
    permalink: /:collection/:path/
    output: true
  essentials:
    permalink: /:collection/:path/
    output: true

# Default layouts
defaults:
  - scope:
      path: ""
      type: libraries
    values:
      layout: default
      parent: Libraries
  - scope:
      path: ""
      type: essentials
    values:
      layout: default
      parent: Essentials

# Search
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: blue

# Buttons
buttons:
  primary:
    color: blue
  secondary:
    color: grey

# Code copy button
enable_copy_code_button: true

# Heading anchors
heading_anchors: true

# Footer links
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/felipepimentel/daggerverse"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 