# ci.yml
name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  id-token: write
  issues: read
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Pipeline
        uses: dagger/dagger-for-github@v7
        with:
          verb: call
          args: detect-modules --source . release-module --source . --token env:GITHUB_TOKEN
          module: ./.dagger/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
