name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  python-pipeline:
    uses: ./.github/workflows/reusable-python-ci.yml
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
