name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  python-pipeline:
    uses: ./.github/workflows/reusable-modules-ci.yml
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    with:
      module-path: "."
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
