name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  version:
    name: Version Management
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioner.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Version Management
        id: versioner
        uses: dagger/dagger-for-github@v7
        with:
          verb: call
          module: github.com/felipepimentel/daggerverse/versioner@main
          args: bump-version --source . --output-version

  python:
    name: Python Pipeline
    needs: [version]
    uses: ./.github/workflows/reusable-python-ci.yml
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      source-path: "."
