name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  python-pipeline:
    uses: ./.github/workflows/reusable-modules-ci.yml
    with:
      module-path: "."
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
