name: "Deploy Documentation"
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
      - ".github/workflows/reusable-docs.yml"

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  docs:
    uses: ./.github/workflows/reusable-docs.yml
    with:
      generator: just-the-docs
      source_dir: docs
      ruby_version: "3.3"
      environment: github-pages
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }} 