name: n8n CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'pipelines/n8n/**'
      - 'pipelines/n8n-digitalocean/**'
      - 'libraries/digitalocean/**'
      - '.github/workflows/n8n-ci-cd.yml'
  pull_request:
    paths:
      - 'pipelines/n8n/**'
      - 'pipelines/n8n-digitalocean/**'
      - 'libraries/digitalocean/**'
      - '.github/workflows/n8n-ci-cd.yml'

jobs:
  n8n-ci-cd:
    uses: ./.github/workflows/reusable-n8n-ci-cd.yml
    secrets:
      digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }} 