name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  detect-changes:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: set-matrix
        run: |
          # Get list of directories containing dagger.json
          MODULES=$(find . -name "dagger.json" -exec dirname {} \; | sed 's|^./||' | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=${MODULES}" >> $GITHUB_OUTPUT

  release:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.matrix != '[]' }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
      fail-fast: false

    name: Release ${{ matrix.module }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec @semantic-release/github

      - name: Get changed files in module
        id: changed-files
        run: |
          # Check if any files in the module path were modified
          git diff --name-only HEAD^ HEAD | grep "^${{ matrix.module }}/" || true
          echo "any_changed=true" >> $GITHUB_OUTPUT

      - name: Set environment variables
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "MODULE_PATH=${{ matrix.module }}" >> $GITHUB_ENV
          echo "MODULE_NAME=${{ matrix.module }}" >> $GITHUB_ENV

      - name: Create Release
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npx semantic-release

      - name: Setup Dagger
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          workdir: ${{ matrix.module }}

      - name: Get latest tag
        if: steps.changed-files.outputs.any_changed == 'true'
        id: get-tag
        run: |
          TAG=$(git describe --tags --abbrev=0 --match "${{ matrix.module }}/v*" || echo "")
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Publish to Daggerverse
        if: steps.changed-files.outputs.any_changed == 'true' && steps.get-tag.outputs.tag != ''
        working-directory: ${{ matrix.module }}
        run: dagger publish
