name: Reusable n8n CI/CD

on:
  workflow_call:
    inputs:
      dagger_version:
        description: 'Version of Dagger to use'
        required: false
        type: string
        default: '0.15.1'
      region:
        description: 'DigitalOcean region'
        required: false
        type: string
        default: 'nyc'
      app_name:
        description: 'n8n app name'
        required: false
        type: string
        default: 'n8n'
      repository:
        description: 'Repository containing the n8n configuration'
        required: true
        type: string
      workdir:
        description: 'Working directory containing the Dagger pipeline. Points to the n8n-digitalocean module in daggerverse.'
        required: false
        type: string
        default: 'pipelines/n8n-digitalocean'
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        description: 'DigitalOcean API token'
        required: true
      DO_SSH_KEY_FINGERPRINT:
        description: 'SSH key fingerprint registered in DigitalOcean'
        required: true
      DO_SSH_KEY_ID:
        description: 'SSH key ID registered in DigitalOcean'
        required: true
      DO_SSH_PRIVATE_KEY:
        description: 'SSH private key for DigitalOcean access'
        required: true
      N8N_BASIC_AUTH_PASSWORD:
        description: 'Password for n8n basic auth'
        required: true
      N8N_DOMAIN:
        description: 'Domain for n8n installation'
        required: true
      N8N_ENCRYPTION_KEY:
        description: 'Encryption key for n8n'
        required: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Daggerverse
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Checkout n8n Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          path: n8n-repo
          fetch-depth: 0

      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H digitalocean.com >> ~/.ssh/known_hosts 2>/dev/null
          ssh-keyscan -H registry.digitalocean.com >> ~/.ssh/known_hosts 2>/dev/null
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: |
            image=moby/buildkit:latest

      - name: Setup Dagger
        uses: dagger/dagger-for-github@v7
        with:
          version: ${{ inputs.dagger_version }}
          
      - name: Cache Dagger
        uses: actions/cache@v3
        with:
          path: ~/.dagger
          key: ${{ runner.os }}-dagger-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-dagger-

      - name: Run CI
        env:
          N8N_BASIC_AUTH_PASSWORD: ${{ secrets.N8N_BASIC_AUTH_PASSWORD }}
          N8N_DOMAIN: ${{ secrets.N8N_DOMAIN }}
          N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}
        run: |
          cd ${{ inputs.workdir }}
          dagger call ci \
            --n8n-repo "../../n8n-repo"

  cd:
    name: CD
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Daggerverse
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Checkout n8n Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          path: n8n-repo
          fetch-depth: 0

      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H digitalocean.com >> ~/.ssh/known_hosts 2>/dev/null
          ssh-keyscan -H registry.digitalocean.com >> ~/.ssh/known_hosts 2>/dev/null
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: |
            image=moby/buildkit:latest

      - name: Setup Dagger
        uses: dagger/dagger-for-github@v7
        with:
          version: ${{ inputs.dagger_version }}
          
      - name: Cache Dagger
        uses: actions/cache@v3
        with:
          path: ~/.dagger
          key: ${{ runner.os }}-dagger-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-dagger-

      - name: Deploy to DigitalOcean
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          SSH_KEY_FINGERPRINT: ${{ secrets.DO_SSH_KEY_FINGERPRINT }}
          SSH_KEY_ID: ${{ secrets.DO_SSH_KEY_ID }}
          N8N_BASIC_AUTH_PASSWORD: ${{ secrets.N8N_BASIC_AUTH_PASSWORD }}
          N8N_DOMAIN: ${{ secrets.N8N_DOMAIN }}
          N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}
        run: |
          cd ${{ inputs.workdir }}
          dagger call deploy \
            --token "$DIGITALOCEAN_TOKEN" \
            --region "${{ inputs.region }}" \
            --app-name "${{ inputs.app_name }}" \
            --ssh-key "$SSH_PRIVATE_KEY" \
            --ssh-key-fingerprint "$SSH_KEY_FINGERPRINT" \
            --ssh-key-id "$SSH_KEY_ID" \
            --domain "$N8N_DOMAIN" \
            --basic-auth-password "$N8N_BASIC_AUTH_PASSWORD" \
            --encryption-key "$N8N_ENCRYPTION_KEY" \
            --n8n-repo "../../n8n-repo"

      - name: Configure Git
        working-directory: n8n-repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync Repository
        working-directory: n8n-repo
        run: |
          git pull origin main
          git add .
          git commit -m "chore(release): sync repository after deployment [skip ci]" || echo "No changes to commit"
          git push origin main 