name: Python CI Pipeline

on:
  workflow_call:
    inputs:
      python-module-version:
        description: "Python module version"
        default: "main"
        required: false
        type: string
      source-path:
        description: "Source code path"
        default: "."
        required: false
        type: string
    secrets:
      PYPI_TOKEN:
        description: "PyPI token for publishing"
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Pipeline
        uses: dagger/dagger-for-github@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        with:
          verb: call
          module: github.com/felipepimentel/daggerverse/python@${{ inputs.python-module-version }}
          args: cicd --source ${{ inputs.source-path }} --token env:PYPI_TOKEN
