name: Modules CI Pipeline

on:
  workflow_call:
    inputs:
      module-path:
        description: "Path to the Dagger module"
        required: false
        type: string
        default: "."
    secrets:
      PYPI_TOKEN:
        description: "PyPI token for publishing"
        required: true
      GH_PAT:
        description: "GitHub Personal Access Token"
        required: true

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Run Pipeline
        uses: dagger/dagger-for-github@v7
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        with:
          verb: call
          module: github.com/felipepimentel/daggerverse/python
          args: cicd --source ${{ inputs.module-path }} --token env:PYPI_TOKEN
