name: Python CI Pipeline

on:
  workflow_call:
    inputs:
      source-path:
        description: "Source code path"
        default: "."
        required: false
        type: string
      dagger-version:
        description: "Dagger version to use"
        default: "0.9.8"
        required: false
        type: string
    secrets:
      PYPI_TOKEN:
        description: "PyPI token for publishing"
        required: true

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write
  packages: write
  statuses: write
  actions: read

jobs:
  pipeline:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
      packages: write
      statuses: write
      actions: read
    outputs:
      version: ${{ steps.versioner.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global --add safe.directory '*'
          git config --global core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic ${{ github.token }}"

      - name: Version Management
        id: versioner
        uses: dagger/dagger-for-github@v7
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          verb: call
          module: github.com/felipepimentel/daggerverse/versioner@main
          args: bump-version --source ${{ inputs.source-path }} --output-version
          version: ${{ inputs.dagger-version }}

      - name: Run Pipeline
        uses: dagger/dagger-for-github@v7
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          VERSION: ${{ steps.versioner.outputs.version }}
        with:
          verb: call
          module: github.com/felipepimentel/daggerverse/python-pipeline@main
          args: cicd --source ${{ inputs.source-path }} --token env:PYPI_TOKEN --version env:VERSION
          version: ${{ inputs.dagger-version }}
