name: Reusable n8n CI/CD

on:
  workflow_call:
    inputs:
      dagger_version:
        description: 'Version of Dagger to use'
        required: false
        type: string
        default: '0.15.2'
      source_path:
        description: 'Path to n8n configuration files'
        required: false
        type: string
        default: '.'
      region:
        description: 'DigitalOcean region'
        required: false
        type: string
        default: 'nyc'
      app_name:
        description: 'n8n app name'
        required: false
        type: string
        default: 'n8n'
      deploy:
        description: 'Whether to deploy to DigitalOcean'
        required: false
        type: boolean
        default: false
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        description: 'DigitalOcean API token'
        required: true
      DO_SSH_KEY_FINGERPRINT:
        description: 'SSH key fingerprint registered in DigitalOcean'
        required: true
      DO_SSH_KEY_ID:
        description: 'SSH key ID registered in DigitalOcean'
        required: true
      DO_SSH_PRIVATE_KEY:
        description: 'SSH private key for DigitalOcean access'
        required: true
      N8N_BASIC_AUTH_PASSWORD:
        description: 'Password for n8n basic auth'
        required: false
      N8N_DOMAIN:
        description: 'Domain for n8n installation'
        required: true
      N8N_ENCRYPTION_KEY:
        description: 'Encryption key for n8n'
        required: false

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write
  packages: write
  statuses: write
  actions: read

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Daggerverse
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Run n8n Pipeline
        uses: dagger/dagger-for-github@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          DO_SSH_KEY_FINGERPRINT: ${{ secrets.DO_SSH_KEY_FINGERPRINT }}
          DO_SSH_KEY_ID: ${{ secrets.DO_SSH_KEY_ID }}
          DO_SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          N8N_BASIC_AUTH_PASSWORD: ${{ secrets.N8N_BASIC_AUTH_PASSWORD }}
          N8N_DOMAIN: ${{ secrets.N8N_DOMAIN }}
          N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}
        with:
          verb: call
          module: github.com/felipepimentel/daggerverse/pipelines/n8n-digitalocean@main
          args: >-
            ${{ inputs.deploy && 'deploy' || 'ci' }}
            --source ${{ inputs.source_path }}
            --region "${{ inputs.region }}"
            --app-name "${{ inputs.app_name }}"
            --token "env:DIGITALOCEAN_TOKEN"
            --domain "env:N8N_DOMAIN"
            --basic-auth-password "env:N8N_BASIC_AUTH_PASSWORD"
            --encryption-key "env:N8N_ENCRYPTION_KEY"
            --ssh-key "env:DO_SSH_PRIVATE_KEY"
            --ssh-key-fingerprint "env:DO_SSH_KEY_FINGERPRINT"
            --ssh-key-id "env:DO_SSH_KEY_ID"
          version: ${{ inputs.dagger_version }} 