name: Python CI Pipeline

on:
  workflow_call:
    inputs:
      source-path:
        description: "Source code path"
        default: "."
        required: false
        type: string
    secrets:
      PYPI_TOKEN:
        description: "PyPI token for publishing"
        required: true

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write
  packages: write
  statuses: write

jobs:
  pipeline:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
      packages: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Run Pipeline
        uses: dagger/dagger-for-github@v7
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        with:
          verb: call
          module: github.com/felipepimentel/daggerverse/python-pipeline@main
          args: cicd --source ${{ inputs.source-path }} --token env:PYPI_TOKEN
