name: Python CI Pipeline

on:
  workflow_call:
    inputs:
      source-path:
        description: "Source code path"
        default: "."
        required: false
        type: string
      dagger_version:
        description: "Dagger version to use"
        default: "0.9.8"
        required: false
        type: string
    secrets:
      PYPI_TOKEN:
        description: "PyPI token for publishing"
        required: true

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write
  packages: write
  statuses: write
  actions: read

jobs:
  pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Run Python Pipeline
        uses: dagger/dagger-for-github@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        with:
          verb: call
          module: github.com/felipepimentel/daggerverse/python@main
          args: publish --source ${{ inputs.source-path }} --token=env:PYPI_TOKEN
          version: ${{ inputs.dagger_version }}
