name: Reusable n8n CI/CD

on:
  workflow_call:
    inputs:
      dagger_version:
        description: 'Version of Dagger to use'
        required: false
        type: string
        default: '0.15.1'
      region:
        description: 'DigitalOcean region'
        required: false
        type: string
        default: 'nyc'
      app_name:
        description: 'n8n app name'
        required: false
        type: string
        default: 'n8n'
      env_vars:
        description: 'Environment variables for n8n'
        required: false
        type: string
        default: '{"N8N_BASIC_AUTH_ACTIVE": "true", "N8N_BASIC_AUTH_USER": "admin"}'
    secrets:
      digitalocean_token:
        description: 'DigitalOcean API token'
        required: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dagger
        uses: dagger/dagger-for-github@v7
        with:
          version: ${{ inputs.dagger_version }}
          
      - name: Cache Dagger
        uses: actions/cache@v3
        with:
          path: ~/.dagger
          key: ${{ runner.os }}-dagger-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-dagger-

      - name: Run CI
        run: |
          dagger call ci --source .

  cd:
    name: CD
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dagger
        uses: dagger/dagger-for-github@v7
        with:
          version: ${{ inputs.dagger_version }}
          
      - name: Cache Dagger
        uses: actions/cache@v3
        with:
          path: ~/.dagger
          key: ${{ runner.os }}-dagger-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-dagger-

      - name: Deploy to DigitalOcean
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.digitalocean_token }}
        run: |
          dagger call deploy \
            --source . \
            --token "$DIGITALOCEAN_TOKEN" \
            --region "${{ inputs.region }}" \
            --app-name "${{ inputs.app_name }}" \
            --env-vars '${{ inputs.env_vars }}' 